//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CapheCMU.Module.BusinessObjects.ORMDataModel1
{

    public partial class Bangluong : DevExpress.Persistent.BaseImpl.BaseObject
    {
        Nhanvien fNhanvienID;
        [Association(@"BangluongReferencesNhanvien")]
        [DevExpress.Xpo.DisplayName(@"Nhân viên")]
        public Nhanvien NhanvienID
        {
            get { return fNhanvienID; }
            set { SetPropertyValue<Nhanvien>(nameof(NhanvienID), ref fNhanvienID, value); }
        }
        double fThang;
        [DevExpress.Xpo.DisplayName(@"Tháng")]
        public double Thang
        {
            get { return fThang; }
            set { SetPropertyValue<double>(nameof(Thang), ref fThang, value); }
        }
        double fNam;
        [DevExpress.Xpo.DisplayName(@"Năm")]
        public double Nam
        {
            get { return fNam; }
            set { SetPropertyValue<double>(nameof(Nam), ref fNam, value); }
        }
        double fSogioLam;
        [DevExpress.Xpo.DisplayName(@"Số giờ làm")]
        public double SogioLam
        {
            get { return fSogioLam; }
            set { SetPropertyValue<double>(nameof(SogioLam), ref fSogioLam, value); }
        }
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "###,###,###,###,###,###"),
DevExpress.ExpressApp.Model.ModelDefault("EditMask", "###,###,###,###,###,###")]
        [DevExpress.Xpo.DisplayName(@"Lương")]
        [PersistentAlias("[NhanvienID(Mucluong)]")]
        public string Luong
        {
            get { return (string)(EvaluateAlias(nameof(Luong))); }
        }
    }

}
