//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CapheCMU.Module.BusinessObjects.ORMDataModel1
{

    public partial class Donnhap : DevExpress.Persistent.BaseImpl.BaseObject
    {
        Sanpham fSanphamID;
        [Association(@"DonnhapReferencesSanpham")]
        [DevExpress.Xpo.DisplayName(@"Loại sản phẩm")]
        public Sanpham SanphamID
        {
            get { return fSanphamID; }
            set { SetPropertyValue<Sanpham>(nameof(SanphamID), ref fSanphamID, value); }
        }
        Phieunhap fNhapID;
        [Association(@"DonnhapReferencesPhieunhap")]
        [DevExpress.Xpo.DisplayName(@"Phiếu nhập")]
        public Phieunhap NhapID
        {
            get { return fNhapID; }
            set { SetPropertyValue<Phieunhap>(nameof(NhapID), ref fNhapID, value); }
        }
        double fSoluong;
        [DevExpress.Xpo.DisplayName(@"Số lượng")]
        public double Soluong
        {
            get { return fSoluong; }
            set { SetPropertyValue<double>(nameof(Soluong), ref fSoluong, value); }
        }
        decimal fDongia;
        [DevExpress.Xpo.DisplayName(@"Đơn giá")]
        public decimal Dongia
        {
            get { return fDongia; }
            set { SetPropertyValue<decimal>(nameof(Dongia), ref fDongia, value); }
        }
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "###,###,###,###,###,###"),
DevExpress.ExpressApp.Model.ModelDefault("EditMask", "###,###,###,###,###,###")]
        [DevExpress.Xpo.DisplayName(@"Thành tiền")]
        [PersistentAlias("ToDecimal([Soluong]) * [Dongia]")]
        public decimal Thanhtien
        {
            get { return (decimal)(EvaluateAlias(nameof(Thanhtien))); }
        }
    }

}
