//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CapheCMU.Module.BusinessObjects.ORMDataModel1
{

    public partial class HoadonCT : DevExpress.Persistent.BaseImpl.BaseObject
    {
        Hoadon fHoadonID;
        [Association(@"HoadonCTReferencesHoadon")]
        [DevExpress.Xpo.DisplayName(@"Hóa đơn")]
        public Hoadon HoadonID
        {
            get { return fHoadonID; }
            set { SetPropertyValue<Hoadon>(nameof(HoadonID), ref fHoadonID, value); }
        }
        Sanpham fSanPhamID;
        [Association(@"HoadonCTReferencesSanpham")]
        [DevExpress.Xpo.DisplayName(@"Sản phẩm")]
        public Sanpham SanPhamID
        {
            get { return fSanPhamID; }
            set { SetPropertyValue<Sanpham>(nameof(SanPhamID), ref fSanPhamID, value); }
        }
        double fSoluong;
        [DevExpress.Xpo.DisplayName(@"Số lượng")]
        public double Soluong
        {
            get { return fSoluong; }
            set { SetPropertyValue<double>(nameof(Soluong), ref fSoluong, value); }
        }
        decimal fDongia;
        [DevExpress.Xpo.DisplayName(@"Đơn giá")]
        public decimal Dongia
        {
            get { return fDongia; }
            set { SetPropertyValue<decimal>(nameof(Dongia), ref fDongia, value); }
        }
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "###,###,###,###,###,###"),
DevExpress.ExpressApp.Model.ModelDefault("EditMask", "###,###,###,###,###,###")]
        [DevExpress.Xpo.DisplayName(@"Thành tiền")]
        [PersistentAlias("ToDecimal([Soluong]) * [Dongia]")]
        public decimal Thanhtien
        {
            get { return (decimal)(EvaluateAlias(nameof(Thanhtien))); }
        }
        [Association(@"TieuhaoReferencesHoadonCT"), Aggregated]
        public XPCollection<Tieuhao> Tieuhaos { get { return GetCollection<Tieuhao>(nameof(Tieuhaos)); } }
    }

}
