//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CapheCMU.Module.BusinessObjects.ORMDataModel1
{

    public partial class Khachhang : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fHoten;
        [DevExpress.Xpo.DisplayName(@"Họ và tên")]
        public string Hoten
        {
            get { return fHoten; }
            set { SetPropertyValue<string>(nameof(Hoten), ref fHoten, value); }
        }
        string fTheloaikhach;
        [DevExpress.Xpo.DisplayName(@"Thể loại khách")]
        public string Theloaikhach
        {
            get { return fTheloaikhach; }
            set { SetPropertyValue<string>(nameof(Theloaikhach), ref fTheloaikhach, value); }
        }
        string fDienthoai;
        [DevExpress.Xpo.DisplayName(@"Số điện thoại")]
        [DevExpress.Persistent.Validation.RuleUniqueValue]
        public string Dienthoai
        {
            get { return fDienthoai; }
            set { SetPropertyValue<string>(nameof(Dienthoai), ref fDienthoai, value); }
        }
        string fMST;
        [DevExpress.Xpo.DisplayName(@"Mã số thuế")]
        [DevExpress.Persistent.Validation.RuleUniqueValue]
        public string MST
        {
            get { return fMST; }
            set { SetPropertyValue<string>(nameof(MST), ref fMST, value); }
        }
        [Association(@"HoadonReferencesKhachhang"), Aggregated]
        public XPCollection<Hoadon> Hoadons { get { return GetCollection<Hoadon>(nameof(Hoadons)); } }
    }

}
