//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CapheCMU.Module.BusinessObjects.ORMDataModel1
{

    public partial class NhomSP : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fTennhom;
        [DevExpress.Xpo.DisplayName(@"Tên nhóm")]
        public string Tennhom
        {
            get { return fTennhom; }
            set { SetPropertyValue<string>(nameof(Tennhom), ref fTennhom, value); }
        }
        string fPhanloai;
        [DevExpress.Xpo.DisplayName(@"Phân loại")]
        public string Phanloai
        {
            get { return fPhanloai; }
            set { SetPropertyValue<string>(nameof(Phanloai), ref fPhanloai, value); }
        }
        [Association(@"SanphamReferencesNhomSP"), Aggregated]
        public XPCollection<Sanpham> Sanphams { get { return GetCollection<Sanpham>(nameof(Sanphams)); } }
    }

}
