//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CapheCMU.Module.BusinessObjects.ORMDataModel1
{

    public partial class Phieunhap : DevExpress.Persistent.BaseImpl.BaseObject
    {
        Nhacungcap fNCCID;
        [Association(@"PhieunhapReferencesNhacungcap")]
        [DevExpress.Xpo.DisplayName(@"Nhà cung cấp")]
        public Nhacungcap NCCID
        {
            get { return fNCCID; }
            set { SetPropertyValue<Nhacungcap>(nameof(NCCID), ref fNCCID, value); }
        }
        Nhanvien fNhanvienID;
        [Association(@"PhieunhapReferencesNhanvien")]
        [DevExpress.Xpo.DisplayName(@"Nhân viên")]
        public Nhanvien NhanvienID
        {
            get { return fNhanvienID; }
            set { SetPropertyValue<Nhanvien>(nameof(NhanvienID), ref fNhanvienID, value); }
        }
        double fSo;
        [DevExpress.Xpo.DisplayName(@"Phiếu số")]
        public double So
        {
            get { return fSo; }
            set { SetPropertyValue<double>(nameof(So), ref fSo, value); }
        }
        string fNgay;
        [DevExpress.Xpo.DisplayName(@"Ngày nhập")]
        [DevExpress.ExpressApp.Model.ModelDefault("EditMask", "dd/MM/yyyy HH:mm"),
DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0:dd/MM/yyyy HH:mm}")]
        public string Ngay
        {
            get { return fNgay; }
            set { SetPropertyValue<string>(nameof(Ngay), ref fNgay, value); }
        }
        [Association(@"DonnhapReferencesPhieunhap"), Aggregated]
        public XPCollection<Donnhap> Donnhaps { get { return GetCollection<Donnhap>(nameof(Donnhaps)); } }
    }

}
